# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: unquote

before:
  hooks:
    - go mod tidy

builds:
  - id: unquote
    env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: unquote
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X 'github.com/bojanrajkovic/unquote/tui/internal/versioninfo.Version={{.Version}}'
      - -X 'github.com/bojanrajkovic/unquote/tui/internal/versioninfo.Branch={{ if index .Env "BUILD_BRANCH" }}{{ index .Env "BUILD_BRANCH" }}{{ else }}{{ .Branch }}{{ end }}'
      - -X 'github.com/bojanrajkovic/unquote/tui/internal/versioninfo.Commit={{.ShortCommit}}'
      - -X 'github.com/bojanrajkovic/unquote/tui/internal/versioninfo.Date={{.Date}}'

universal_binaries:
  - replace: true

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: []
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-snapshot+{{ .ShortCommit }}"

changelog:
  sort: asc
  use: git
  filters:
    include:
      - "^feat\\(tui"
      - "^fix\\(tui"
    exclude:
      - "^Merge"
  groups:
    - title: Features
      regexp: "^feat\\(tui"
      order: 0
    - title: Bug Fixes
      regexp: "^fix\\(tui"
      order: 1

release:
  github:
    owner: bojanrajkovic
    name: unquote
  draft: false
  prerelease: auto
  mode: keep-existing
  name_template: "unquote {{.Tag}}"
