experimental_monorepo_root = true

[tools]
lefthook = "latest"
"npm:@commitlint/cli" = "latest"
"aqua:zizmorcore/zizmor" = "latest"

[monorepo]
config_roots = ["api", "infra", "tui", "web"]

[tasks.build]
description = "Build all projects"
depends = ["//api:install", "//api:build", "//tui:install", "//tui:build", "//web:install", "//web:build"]
