packages:
  - packages/*

catalogs:
  build:
    '@tsconfig/node24': ^24.0.0
    '@tsconfig/strictest': ^2.0.0
    '@types/luxon': ^3.4.0
    '@types/node': ^24.0.0
    rimraf: ^6.0.0
    tsx: ^4.19.0
    typescript: ^5.8.0
  lint:
    oxfmt: ^0.27.0
    oxlint: ^1.42.0
  prod:
    '@eropple/fastify-openapi3': ^1.0.0
    '@fastify/cors': ^10.0.0
    '@fastify/env': ^5.0.0
    '@fastify/helmet': ^13.0.0
    '@fastify/rate-limit': ^10.0.0
    '@fastify/sensible': ^6.0.0
    '@fastify/type-provider-typebox': ^6.1.0
    '@fastify/under-pressure': ^9.0.0
    '@opentelemetry/api': ^1.9.0
    '@opentelemetry/auto-instrumentations-node': ^0.69.0
    '@opentelemetry/exporter-trace-otlp-http': ^0.211.0
    '@opentelemetry/instrumentation': ^0.211.0
    '@opentelemetry/resources': ^2.5.0
    '@opentelemetry/sdk-node': ^0.211.0
    '@opentelemetry/semantic-conventions': ^1.28.0
    ajv-formats: ^3.0.0
    awilix: ^12.0.0
    fastify: ^5.2.0
    fastify-plugin: ^5.0.0
    luxon: ^3.5.0
    pino: ^10.0.0
    sqids: ^0.3.0
    typebox: ^1.0.13
  testing:
    '@vitest/coverage-v8': ^3.0.0
    ajv: ^8.0.0
    fast-check: ^3.0.0
    nanoid: ^5.1.6
    vitest: ^3.0.0

injectWorkspacePackages: true

patchedDependencies:
  ajv-formats@3.0.1: patches/ajv-formats@3.0.1.patch
