packages:
  - "packages/*"

catalogs:
  build:
    "@tsconfig/strictest": "^2.0.0"
    "@tsconfig/node24": "^24.0.0"
    "@types/node": "^20.0.0"
    typescript: "^5.8.0"
    tsx: "^4.19.0"
  lint:
    oxlint: "^1.42.0"
    oxfmt: "^0.27.0"
  testing:
    vitest: "^3.0.0"
    "@vitest/coverage-v8": "^3.0.0"
  prod:
    fastify: "^5.2.0"
    "@eropple/fastify-openapi3": "^1.0.0"
    "@fastify/type-provider-typebox": "^5.0.0"
    "@sinclair/typebox": "^0.34.0"
    "@fastify/helmet": "^13.0.0"
    "@fastify/cors": "^10.0.0"
    "@fastify/under-pressure": "^9.0.0"
    "@fastify/sensible": "^6.0.0"
    "@fastify/rate-limit": "^10.0.0"
